trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

resources:
  containers:
  - container: rpc-arduino
    image: commonwealthrobotics/rpc-arduino:latest

stages:
- stage: Build
  jobs:
    - job: Linux

      pool:
        vmImage: ubuntu-18.04

      steps:
        - bash: "platformio run"
          displayName: "Build"
